// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: srv/consignment/proto/consignment/consignment.proto

package go_micro_srv_consignment

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Consignment service

type ConsignmentService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Consignment_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Consignment_PingPongService, error)
}

type consignmentService struct {
	c    client.Client
	name string
}

func NewConsignmentService(name string, c client.Client) ConsignmentService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.consignment"
	}
	return &consignmentService{
		c:    c,
		name: name,
	}
}

func (c *consignmentService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Consignment.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consignmentService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Consignment_StreamService, error) {
	req := c.c.NewRequest(c.name, "Consignment.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &consignmentServiceStream{stream}, nil
}

type Consignment_StreamService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type consignmentServiceStream struct {
	stream client.Stream
}

func (x *consignmentServiceStream) Close() error {
	return x.stream.Close()
}

func (x *consignmentServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *consignmentServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *consignmentServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *consignmentService) PingPong(ctx context.Context, opts ...client.CallOption) (Consignment_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Consignment.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &consignmentServicePingPong{stream}, nil
}

type Consignment_PingPongService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type consignmentServicePingPong struct {
	stream client.Stream
}

func (x *consignmentServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *consignmentServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *consignmentServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *consignmentServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *consignmentServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Consignment service

type ConsignmentHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Consignment_StreamStream) error
	PingPong(context.Context, Consignment_PingPongStream) error
}

func RegisterConsignmentHandler(s server.Server, hdlr ConsignmentHandler, opts ...server.HandlerOption) error {
	type consignment interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Consignment struct {
		consignment
	}
	h := &consignmentHandler{hdlr}
	return s.Handle(s.NewHandler(&Consignment{h}, opts...))
}

type consignmentHandler struct {
	ConsignmentHandler
}

func (h *consignmentHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.ConsignmentHandler.Call(ctx, in, out)
}

func (h *consignmentHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.ConsignmentHandler.Stream(ctx, m, &consignmentStreamStream{stream})
}

type Consignment_StreamStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type consignmentStreamStream struct {
	stream server.Stream
}

func (x *consignmentStreamStream) Close() error {
	return x.stream.Close()
}

func (x *consignmentStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *consignmentStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *consignmentStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *consignmentHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.ConsignmentHandler.PingPong(ctx, &consignmentPingPongStream{stream})
}

type Consignment_PingPongStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type consignmentPingPongStream struct {
	stream server.Stream
}

func (x *consignmentPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *consignmentPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *consignmentPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *consignmentPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *consignmentPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
