// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: srv/vessel/proto/vessel/vessel.proto

package go_micro_srv_vessel

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Vessel service

type VesselService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Vessel_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Vessel_PingPongService, error)
}

type vesselService struct {
	c    client.Client
	name string
}

func NewVesselService(name string, c client.Client) VesselService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.vessel"
	}
	return &vesselService{
		c:    c,
		name: name,
	}
}

func (c *vesselService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Vessel.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vesselService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Vessel_StreamService, error) {
	req := c.c.NewRequest(c.name, "Vessel.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &vesselServiceStream{stream}, nil
}

type Vessel_StreamService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type vesselServiceStream struct {
	stream client.Stream
}

func (x *vesselServiceStream) Close() error {
	return x.stream.Close()
}

func (x *vesselServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *vesselServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *vesselServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *vesselService) PingPong(ctx context.Context, opts ...client.CallOption) (Vessel_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Vessel.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &vesselServicePingPong{stream}, nil
}

type Vessel_PingPongService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type vesselServicePingPong struct {
	stream client.Stream
}

func (x *vesselServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *vesselServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *vesselServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *vesselServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *vesselServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Vessel service

type VesselHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Vessel_StreamStream) error
	PingPong(context.Context, Vessel_PingPongStream) error
}

func RegisterVesselHandler(s server.Server, hdlr VesselHandler, opts ...server.HandlerOption) error {
	type vessel interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Vessel struct {
		vessel
	}
	h := &vesselHandler{hdlr}
	return s.Handle(s.NewHandler(&Vessel{h}, opts...))
}

type vesselHandler struct {
	VesselHandler
}

func (h *vesselHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.VesselHandler.Call(ctx, in, out)
}

func (h *vesselHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.VesselHandler.Stream(ctx, m, &vesselStreamStream{stream})
}

type Vessel_StreamStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type vesselStreamStream struct {
	stream server.Stream
}

func (x *vesselStreamStream) Close() error {
	return x.stream.Close()
}

func (x *vesselStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *vesselStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *vesselStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *vesselHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.VesselHandler.PingPong(ctx, &vesselPingPongStream{stream})
}

type Vessel_PingPongStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type vesselPingPongStream struct {
	stream server.Stream
}

func (x *vesselPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *vesselPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *vesselPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *vesselPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *vesselPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
